{
 "title": "AmLight-INT",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "500ms",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "This row shows the amount of data exchanged in mega bytes in the time interval specified in the field.\n         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VLAN 309 in MB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "port_tx_utilization_octets,sw_id=4217755253,eg_id=0,queue_id=0",
     "query": "SELECT  value/(1024*1024) FROM \"port_tx_utilization_octets,sw_id=4217755253,eg_id=11,queue_id=0,vlan_id=309\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "port_tx_utilization_octets,sw_id=4217755253,eg_id=0,queue_id=0",
     "query": "SELECT  value/(1024*1024) FROM \"port_tx_utilization_octets,sw_id=4217755253,eg_id=12,queue_id=0,vlan_id=309\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VLAN 1150 in MB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "port_tx_utilization_octets,sw_id=4217755253,eg_id=0,queue_id=0",
     "query": "SELECT  value/(1024*1024) FROM \"port_tx_utilization_octets,sw_id=4217755253,eg_id=11,queue_id=0,vlan_id=1150\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "port_tx_utilization_octets,sw_id=4217755253,eg_id=0,queue_id=0",
     "query": "SELECT  value/(1024*1024) FROM \"port_tx_utilization_octets,sw_id=4217755253,eg_id=12,queue_id=0,vlan_id=1150\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 0 },
   "options": {
    "content": "This row shows the traffic summing up all ports at AmLight\n         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Traffic at AmLight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "port_tx_utilization_octets,sw_id=4217755253,eg_id=0,queue_id=0",
     "query": "SELECT  derivative(max(\"value\"),1s)*8 FROM /port_tx_utilization_octets,sw_id=.*,eg_id=.*,queue_id=.*,vlan_id=.*/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VLAN 1117 in MB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "port_tx_utilization_octets,sw_id=4217755253,eg_id=0,queue_id=0",
     "query": "SELECT  value/(1024*1024) FROM \"port_tx_utilization_octets,sw_id=4217755253,eg_id=11,queue_id=0,vlan_id=1117\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "port_tx_utilization_octets,sw_id=4217755253,eg_id=0,queue_id=0",
     "query": "SELECT  value/(1024*1024) FROM \"port_tx_utilization_octets,sw_id=4217755253,eg_id=12,queue_id=0,vlan_id=1117\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VLAN 3500 in MB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "port_tx_utilization_octets,sw_id=4217755253,eg_id=0,queue_id=0",
     "query": "SELECT  value/(1024*1024) FROM \"port_tx_utilization_octets,sw_id=4217755253,eg_id=11,queue_id=0,vlan_id=3500\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "port_tx_utilization_octets,sw_id=4217755253,eg_id=0,queue_id=0",
     "query": "SELECT  value/(1024*1024) FROM \"port_tx_utilization_octets,sw_id=4217755253,eg_id=12,queue_id=0,vlan_id=3500\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Per-Flow Egress Utilization - Bits per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "port_tx_utilization_octets,sw_id=4217755253,eg_id=0,queue_id=0",
     "query": "SELECT  derivative(max(\"value\"),1s)*8 FROM /port_tx_utilization_octets,sw_id=.*,eg_id=.*,queue_id=.*,vlan_id=.*/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Per-Queue Egress Utilization - Bits per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "port_tx_utilization_octets,sw_id=4217755253,eg_id=0,queue_id=0",
     "query": "SELECT  derivative(max(\"value\"),1s)*8 FROM /port_tx_utilization_octets_queue,sw_id=.*,eg_id=.*,queue_id=.*/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "port_tx_utilization_octets,sw_id=4217755253,eg_id=0,queue_id=0",
     "query": "SELECT  derivative(max(\"value\"),1s)*8 FROM /port_tx_utilization_octets_int,sw_id=.*,eg_id=.*/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Per-Flow Egress Utilization - Packets per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  derivative(max(\"value\"),1s) FROM /port_tx_utilization_pkts,sw_id=4217755253,eg_id=.*,queue_id=.*/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Egress Interfaces' Queue Occupancy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") * 80 FROM /queue_occupancy,sw_id=4217755253,eg_id=.*,queue_id=.*/ WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hop Delay for MIA-MI1-SW10 - All Flows",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ns", "label": "Delay" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM /flow_hop_latency,vlan_id=.*,sw_id=4217755253,eg_id=.*,sw_hop=4217755253/ WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telemetry Packets per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "Total Number of INT Reports Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_packet_counter,type=0",
     "query": "SELECT derivative(max(\"value\"),1s) FROM \"telemetry_packet_counter,type=0\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Number of Alerts Generated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_packet_counter,type=0",
     "query": "SELECT derivative(max(\"value\"),1s) FROM \"telemetry_packet_counter,type=2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}